# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - secret-detection
  - build
  - deploy
  - mirror

# Jobs de sécurité existants
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: "true"

# Job de déploiement vers Vercel
.default_node_job:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store

build:
  stage: build
  extends: .default_node_job
  script:
    - pnpm install --frozen-lockfile
    - pnpm run build
  only:
    - main

deploy:
  stage: deploy
  extends: .default_node_job
  needs: ["build"]
  script:
    - pnpm install --frozen-lockfile
    - pnpm dlx vercel --prod --confirm --token $VERCEL_TOKEN

  only:
    - main

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

# Job de mirroring optimisé
mirror_to_github:
  needs: ["deploy"]
  stage: mirror
  image: debian:stable
  before_script:
    - apt-get update && apt-get install -y git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - tr -d '\r' < ~/.ssh/id_rsa > ~/.ssh/id_rsa.clean && mv ~/.ssh/id_rsa.clean ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts

    # IMPORTANT : GitLab CI ne crée pas la branche main → on la recrée
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - git fetch origin main
    - git checkout -B main origin/main

    # Remote GitHub
    - git remote remove github || true
    - git remote add github git@github.com:Karvaneg/portfolio-karvaneg.git

  script:
    - GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' git push github main --force
    - GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' git push github --tags --force

  only:
    - main
